DATABASE employee-management IF NOT EXISTS 
CREATE DATABASE employee-management IF NOT EXISTS ,

CREATE TABLE department (
id INT AUTO_INCREMENT NOT NULL ,
name VARCHAR(30) NOT NULL ,
PRIMARY KEY(id) ,
) ,

CREATE TABLE role (
	id INT AUTO_INCREMENT NOT NULL ,
    title VARCHAR(30) , 
    PRIMARY KEY(id) ,
)
 